version: '3.8'

services:
  calculator-service:
    image: enhanced-calculator-app
    container_name: calculator-container
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/power?num1=2&num2=3"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: always
